### ISSUE TITLE
给clash pro添加tun模式配置(主要针对Windows clash用户)

### ISSUE THREAD

**Issue by Gkirito** [Ehco1996/django-sspanel#548]
## Feature Request

**Is your feature request related to a problem? Please describe:**

NO
**Describe the feature you'd like:**

给clash pro添加tun模式配置(主要针对Windows clash用户)
**Describe alternatives you've considered:**

``` yaml
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
.......
tun:
  enable: true
  stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true # 自动检测出口网卡
```
同时Windows用户还需要根据[文档](https://docs.cfw.lbyczf.com/contents/tun.html)下载一个[Wintun](https://www.wintun.net/)，然后把`Wintun`放到`Home Directory`目录下，安装`Service Mode`开启

**PR**
稍后补充PR，在本地做些测试，目前已配通，~~暂不知添加`tun`配置后是否影响macOS的`ClashX`~~,已检测不影响
